version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - red-app

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - red-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod

networks:
  red-app:
